name: Sync to Hugging Face Space
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://sdd-2396:$LEADGENERATION@huggingface.co/spaces/sdd-2396/LeadGenerationAgent main
       
         
